[package]
name = "vsock"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(target_os = "hermit")'.dependencies.hermit-abi]
path = "../../hermit-abi"

[target.'cfg(target_os = "hermit")'.dependencies.hermit]
path = "../../hermit"
default-features = false

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2" }

[features]
default = ["hermit/pci", "hermit/pci-ids", "hermit/acpi", "hermit/vsock"]
client = []
