name: CI

on:
  pull_request:
  merge_group:

env:
  GH_TOKEN: ${{ github.token }}
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: mkroening/rust-toolchain-toml@main
        with:
          targets: x86_64-unknown-none
      - run: |
          rustup component add clippy llvm-tools
          rustup target add wasm32-wasip1
      - name: Clippy
        run: |
          cargo clippy --all-targets
          cargo clippy -Zbuild-std=std,panic_abort --target=x86_64-unknown-hermit --all-targets
          cargo clippy -Zbuild-std=std,panic_abort --target=aarch64-unknown-hermit --all-targets
          cargo clippy -Zbuild-std=std,panic_abort --target=riscv64gc-unknown-hermit --all-targets
          cargo clippy -Zbuild-std=std,panic_abort --target=x86_64-unknown-hermit --package hermit --features common-os

  format:
    name: Format
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - uses: mkroening/rust-toolchain-toml@main
      - run: rustup component add rustfmt
      - name: Format
        run: cargo fmt -- --check

  check-docs:
    name: Check docs
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: mkroening/rust-toolchain-toml@main
        with:
          targets: x86_64-unknown-none
      - run: |
          rustup component add llvm-tools
          rustup target add wasm32-wasip1
      - name: Check docs
        run: cargo doc --no-deps --document-private-items

  run-hermit:
    name: Run
    runs-on: ubuntu-26.04
    defaults:
      run:
        working-directory: kernel
    strategy:
      matrix:
        arch: [x86_64, aarch64, riscv64]
        profile: [dev, release]
        include:
          - arch: x86_64
            packages: qemu-system-x86-hwe
            flags: --accel --sudo
          - arch: aarch64
            packages: qemu-system-arm-hwe
          - arch: riscv64
            packages: qemu-system-riscv-hwe
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends ipxe-qemu libcap-ng-dev libseccomp-dev ${{ matrix.packages }}
      - name: Download loader
        run: gh release download --repo hermit-os/loader --pattern 'hermit-loader-${{ matrix.arch }}*'
      - uses: mkroening/rust-toolchain-toml@main
      - uses: mkroening/rust-toolchain-toml@main
        with:
          toolchain-file: 'kernel/rust-toolchain.toml'
      - run: rustup target add wasm32-wasip1
        working-directory: .
      - run: cargo +stable install --locked virtiofsd
        if: matrix.arch == 'x86_64'
      - run: cargo xtask ci rs --arch ${{ matrix.arch }} --profile ${{ matrix.profile }} --features hermit/loader --package rusty_demo qemu ${{ matrix.flags }}
      - run: cargo xtask ci rs --arch ${{ matrix.arch }} --profile ${{ matrix.profile }} --features hermit/loader --package httpd --features ci,hermit/dhcpv4,hermit/virtio-net qemu ${{ matrix.flags }} --devices virtio-net-pci
      - run: cargo xtask ci rs --arch ${{ matrix.arch }} --profile ${{ matrix.profile }} --features hermit/loader --package miotcp --features hermit/dhcpv4,hermit/virtio-net qemu ${{ matrix.flags }} --devices virtio-net-pci
      - run: cargo xtask ci rs --arch ${{ matrix.arch }} --profile ${{ matrix.profile }} --features hermit/loader --package mioudp --features hermit/udp,hermit/dhcpv4,hermit/virtio-net qemu ${{ matrix.flags }} --devices virtio-net-pci
      - run: |
          cd ..
          cargo build --target wasm32-wasip1 --profile release --package hello_world
          mkdir kernel/shared
          cp target/wasm32-wasip1/release/hello_world.wasm kernel/shared
          cd kernel
          cargo xtask ci rs --arch ${{ matrix.arch }} --profile ${{ matrix.profile }} --features hermit/loader --package hermit-wasm --features fs qemu ${{ matrix.flags }} --devices virtio-fs-pci
        if: matrix.arch == 'x86_64'
