name: KVM Tests

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

jobs:
  kvm:
    name: KVM Tests
    runs-on: [self-hosted]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with: 
         rust-version: nightly
         components: 'rust-src, llvm-tools-preview'
         targets: 'x86_64-unknown-linux-gnu'
    - uses: actions/checkout@v2.3.4
      with:
         submodules: true
    - name: Check Cargo availability
      run: cargo --version
    - name: Build (debug)
      run:
         cargo build -p rusty_demo
    - name: Build (release)
      run:
         cargo build -p rusty_demo --release
    - name: Check test environment
      shell: bash
      run: |
         lscpu
         kvm-ok
         cargo install --git https://github.com/hermitcore/uhyve.git
    - name: Test debug version
      run:
         RUST_LOG=debug uhyve -v -c 1 target/x86_64-unknown-hermit/release/rusty_demo
    - name: Test release version
      run:
         RUST_LOG=debug uhyve -v -c 1 target/x86_64-unknown-hermit/release/rusty_demo
